---
title: "Blog-Wrangling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align="center")
library(tidyverse)
library(dplyr)
library(rvest)
#plays <- read_csv("C:/~git/Old-Blog-ESPN/DATA/plays.csv")
#week1 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week1.csv")
#week2 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week2.csv")
#week3 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week3.csv")
#week4 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week4.csv")
#week5 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week4.csv")
#week6 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week6.csv")
#week7 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week7.csv")
#week8 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week8.csv")
#week9 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week9.csv")
#week10 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week10.csv")
#week11 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week11.csv")
#week12 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week12.csv")
#week13 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week13.csv")
#week14 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week14.csv")
#week15 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week15.csv")
#week16 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week16.csv")
#week17 <- read_csv("C:/~git/Old-Blog-ESPN/DATA/week17.csv") 

#plays <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/plays.csv")
#week1 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week1.csv")
#week2 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week2.csv")
#week3 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week3.csv")
#week4 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week4.csv")
#week5 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week4.csv")
#week6 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week6.csv")
#week7 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week7.csv")
#week8 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week8.csv")
#week9 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week9.csv")
#week10 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week10.csv")
#week11 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week11.csv")
#week12 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week12.csv")
#week13 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week13.csv")
#week14 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week14.csv")
#week15 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week15.csv")
#week16 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week16.csv")
#week17 <- read_csv("/Users/seandube/git/DATA/nfl-big-data-bowl-2021/week17.csv")

#plays <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/plays.csv")
#week1 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week1.csv")
#week2 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week2.csv")
#week3 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week3.csv")
#week4 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week4.csv")
#week5 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week4.csv")
#week6 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week6.csv")
#week7 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week7.csv")
#week8 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week8.csv")
#week9 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week9.csv")
#week10 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week10.csv")
#week11 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week11.csv")
#week12 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week12.csv")
#week13 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week13.csv")
#week14 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week14.csv")
#week15 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week15.csv")
#week16 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week16.csv")
#week17 <- read_csv("/Users/damienruparel/git/BLOG-ESPN/nfl-big-data-bowl-2021/week17.csv")






weeks <- combine(week1, week2, week3, week4, week5, week6, week7, week8, week9, week10, week11, week12, week13, week14, week15, week16, week17)
#wrangle

week1edit <- weeks %>%
  filter(event != "None") %>%
  select(x,y,event, nflId, displayName, position, team, gameId, playId, playDirection)%>%
  group_by(gameId, playId) %>%
  right_join(plays, week1edit, by = c("playId", "gameId")) %>%
  filter(event != "NA")

PassStats <- plays %>%
  select(possessionTeam, yardsToGo, passResult, offensePlayResult) %>%
  rename(Team = possessionTeam, Result = passResult, yardsGained = offensePlayResult) %>%
  group_by(Team, Result) %>%
  summarise(n=n(), TotalYards = sum(yardsGained)) %>%
  rename(ResultCount = n) %>%
  filter(Result != "NA" & Result != "R" & Result != "S")
 
CompletionPercentage <- PassStats %>%
  group_by(Team) %>%
  summarise(Percentage = (ResultCount / sum(ResultCount) )* 100, AverageYards = TotalYards / sum(ResultCount)) %>%
  mutate(AverageYards = round(AverageYards, 2)) %>%
  mutate(Percentage = round(Percentage, 2)) %>%
  slice(1) %>%
  ungroup() 


#filter the events needed
plot <- week1edit %>%
  filter(event == "ball_snap" | event == "pass_outcome_incomplete" | event == "tackle" | event == "out_of_bounds" | event == "touchdown") %>%
  filter(displayName == "Football")

plot1other <- plot %>%
  filter(event != "tackle")%>%
  filter(event != "out_of_bounds")

plot1endplay <- plot %>%
  filter(event == "tackle" | event == "out_of_bounds")%>%
  mutate(event = "end_of_play")

plot1 <- combine(plot1other, plot1endplay)


#categorizing the yards to go 
plot1short <- plot1 %>%
  filter(yardsToGo <= 3) %>%
  mutate(togo = "short")

plot1med <- plot1 %>%
  filter(yardsToGo >= 3 & yardsToGo < 8) %>%
  mutate(togo = "medium")

plot1long <- plot1 %>%
  filter(yardsToGo >= 8) %>%
  mutate(togo = "long")

plot1 <- combine(plot1short, plot1med, plot1long)


#first down
plot1final <- plot1 %>%
  mutate(firstdownnum = playResult - yardsToGo)

firstdown_y <- plot1final %>%
  filter(firstdownnum >= 0)%>%
  mutate(firstdown = 1)

firstdown_n <- plot1final %>%
  filter(firstdownnum < 0)%>%
  mutate(firstdown = 0)

plot1final <- combine(firstdown_n, firstdown_y)



plot1finished <- plot1final %>%
  select(gameId, playId, event, down, yardsToGo, playDirection, absoluteYardlineNumber, playResult, togo, x, y, firstdown)

write_csv(plot1finished, "plot1finished.csv")
write_csv(PassStats, "PassStats.csv")
write_csv(CompletionPercentage, "CompletionPercentage.csv")
```

```{r}
plot2touchdown <- plot1finished %>%
  filter(event == "touchdown")%>%
  mutate(touchdown = 1)%>%
  select(gameId, playId, touchdown)

plot2 <- plot2touchdown %>%
   right_join(plot1finished, plot2touchdown, by = c("playId", "gameId")) %>%
   mutate_all(funs(ifelse(is.na(.), 0, .)))

plot2completion <- plot1finished %>%
  filter(event == "touchdown" | event == "end_of_play")%>%
  mutate(completion = 1)%>%
  select(gameId, playId, completion)

plot2 <- plot2completion %>%
   right_join(plot2, plot2completion, by = c("playId", "gameId")) %>%
   mutate_all(funs(ifelse(is.na(.), 0, .)))

  
plot2finished <- plot2 %>%
  select(gameId, playId, down, togo, touchdown, completion, playResult, event, absoluteYardlineNumber, playDirection)%>%
  filter(event == "ball_snap")

plot2finished <- plot2finished %>%
  group_by(down, togo, absoluteYardlineNumber, playDirection)%>%
  summarise(TouchdownPercentage = mean(touchdown), CompletionPercentage = mean(completion), AverageYards = mean(playResult))%>%
  mutate(TouchdownPercentage = round(TouchdownPercentage,2))%>%
  mutate(CompletionPercentage = round(CompletionPercentage,2))%>%
  mutate(AverageYards = round(AverageYards,2))

write_csv(plot2finished, "plot2finished.csv")
```



```{r}
url_NFL18 <- "https://www.nfl.com/standings/league/2018/reg/"
tables_NFL18 <- url_NFL18 %>%read_html()%>%html_nodes("table")
length(tables_NFL18)
NFL18 <- html_table(tables_NFL18[[1]])
NFL18 <- NFL18 %>%
  select(`NFL Team`, W, L, `T`)

NFLteams <- c("ARI", "NYJ", "OAK", "SF", "JAX", "NYG", "TB", "BUF", "CIN", "DEN", "DET", "GB", "ATL", "CAR", "CLE", "MIA", "WAS", "MIN", "PHI",
              "PIT", "TEN", "BAL", "DAL", "IND", "SEA", "HOU", "NE", "CHI", "KC", "LAC", "LA", "NO")

NFL <- as.data.frame(NFLteams)

NFL1 <- cbind(NFL18, Team=NFLteams)

Teamstats <- right_join(NFL1,CompletionPercentage , by = "Team")


write_csv(Teamstats, "Teamstats.csv")

```